Update: Support embed
gin-contrib/i18n pull request #3
Opened 2021-11-30 04:48 UTC by whimthen

2021-11-30 05:23 UTC, thinkerou commented
@whimthen please add some unit test, thanks!

2021-11-30 06:39 UTC, whimthen commented
> @whimthen please add some unit test, thanks!

Unit test has been added.

2021-12-09 15:11 UTC, appleboy requested changes

2021-12-09 15:11 UTC, appleboy commented on i18n.go
> +	//ins.setBundle(defaultBundleConfig)
remove unused code.

2022-03-06 11:51 UTC, Charliego93 reviewed
Reviewed it.

2022-03-06 13:39 UTC, appleboy commented
@Charliego93 Please fix the build error.

2022-03-08 14:54 UTC, shuntagami commented
I want this feature. Thanks!

2022-03-09 08:43 UTC, Charliego93 commented
> I want this feature. Thanks!

I have no time check it for now. It's later. Maybe you can use my another package https://github.com/Charliego93/go-i18n

2022-03-09 08:59 UTC, shuntagami commented
@Charliego93 
Thanks for your work. I'll check it later.

@appleboy
May I work on this PR instead?

2022-03-10 04:55 UTC, appleboy commented
@shuntagami OK, Great. Go ahead. Thanks

2022-03-11 17:45 UTC, Charliego93 commented
@appleboy I just saw the build error because embed is not supported until 1.16, workflow strategy need to be modified. Can I modify it?

2022-03-12 02:05 UTC, appleboy commented
@Charliego93 You can add a build tag (`//go:build`) to separate multiple versions. see https://kofo.dev/build-tags-in-golang

2022-03-12 04:45 UTC, appleboy commented
@Charliego93 closed via https://github.com/gin-contrib/i18n/pull/7

2022-03-12 04:45 UTC, closed without merging